[package]
name = "uuid"
version = "0.1.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }

[dependencies.rocket_contrib]
default-features = false
path = "../../contrib/lib"
features = ["uuid"]
